### ISSUE TITLE
Assignment 2: Cosine Similarity Doc test

### ISSUE THREAD

**Issue by abrarshivani** [iit-cs429/main#127]
Hi Prof,

Shouldn't the doctest of cosine similarity result to 0.3782890 instead of 0.792857.

Thanks,
Abrar

**Comment by changediyasunny** [comment]
Yes i too have same answer.  it should return 0.378  according to cosine similarity concept.

**Comment by aronwc** [comment]
The tf-idf value for a term/document pair is
```
(1 + log(tf)) * log(N/df)
```
The first document is `['a a b c']`. So, the term `a` has `tf=2` and `df=1`; thus, its tf-idf value is `(1 + log10(2)) * log(3/1) =  .6207...`. We multiply this by the provided query weight for this term (1). Thus, the numerator in the cosine similarity is .6207.... The denominator is the precomputed doc norm for document 1 (0.782927). Then, the final value is `.6207... / .782927 = 0.792857`. Recall that we don't need to divide by the query norm, since this will not affect the final ranking.

**Comment by skrzepto** [comment]
What professor posted worked for me I was using one variable wrong but the example posted cleared things up and is working.

**Comment by aronwc** [comment]
Closing -- reopen if needed
