### ISSUE TITLE
Scores

### ISSUE THREAD

**Issue by cgarciahdez** [iit-cs429/main#136]
I am having some small differences in the order of the documents, I am guessing its because of the float point comparison, but this happens even after rounding them up to 6 decimals. Do you have any idea how to fix this? Most of the time it only changes the position of two adjacent docs ids.

**Comment by changediyasunny** [comment]
Yeah, It is due to floating point comparison. but if you have rounded them up to 6 decimal places then it should work. Check with python3 in case if you are using older version of Python . or I would suggest to check top 10 (doc_id, val) pair (sorted order) in a dict returned by search() function from main.py and check whether the same are doc_id's are getting reflected in final output.
