### ISSUE TITLE
Interpolation/Dirichlet smoothin

### ISSUE THREAD

**Issue by tmarkov** [iit-cs429/main#138]
With tf-idf, each query term is scored as
**log(idf)*(1+log (tf)).**
With Dirichlet interpolation, a term is scored by
**(if+a*cf/T)/(a+L)**
And with interpolation smoothing, we have
**a*tf/L + (1-a)*cf/T**

Since collection frequency is highly correlated with document frequency, I notice that high document frequency penalizes the term score if the term has high document frequency (which makes sense). However, language models BOOST the scores of terms that have high collection frequency, which seems illogical to do. Can you elaborate more on why do we use formulas that boost the score of words with high document/collection frequency?

**Comment by aronwc** [comment]
It appears to be boosting such terms, but in fact it does not. The reason
for this apparent contradiction is that for tfidf, only terms present in
both the query and document are considered. In contrast, in language
models, terms in the query but not in the document contribute to the final
score.

For example, in the interpolated LM, the cf/T term has the effect of
smoothing "more" for common terms.

q=the dog

d1: the cat
d2: a dog

Assume lambda=.8, cf(the)=100, cf(dog)=5, and T=200

P(the dog|d1) = P(the|d1) * P(dog|d1) = [.8(.5) + .2(.5)] * [.8(0) +
.2(5/200)] = .0025

P(the dog|d2) = P(the|d2) * P(dog|d2) = [.8(0) + .2(.5)] *  [.8(.5) +
.2(5/200)] = .0405

So, even though both d1 and d2 match one term from the query, d2 is ranked
higher since it matches the less common term ("dog").

-Aron

**Comment by tmarkov** [comment]
Ah, and smoothing more actually means it matters less. I see. Thanks.
