### ISSUE TITLE
Ada Lovelace Example Different

### ISSUE THREAD

**Issue by sdimitro** [iit-cs429/main#161]
Hi professor,

You mention in the comment of get_links that for Ada we should get the following:

> inlinks['Ada_Lovelace'] = SortedSet(['Charles_Babbage', 'David_Gelernter']
> and
> outlinks['Ada_Lovelace'] = SortedSet(['Alan_Turing', 'Charles_Babbage']
> (also taking out Ada from the list)

I do get these names but I also get one extra name for each set:

> inlinks['Ada_Lovelace'] = SortedSet(['Charles_Babbage', 'David_Gelernter', 'Margaret_Hamilton_(scientist)']
> and
> outlinks['Ada_Lovelace'] = SortedSet(['Alan_Turing', 'Charles_Babbage', 'Stephen Wolfram']

I also checked Ada's page and I can find for example Wolfram's Link.

Is there any case that your comment is outdated or is it a problem on my side?

Thank you

**Comment by pbhagav1** [comment]
I think the Stephen Wolfram's link is his personal website, and the html pages we are considering over here belong to wiki. So I feel that we need to consider only "/wiki/<scientist_name>" links present in the html page. Similarly, in the 'Margaret_Hamilton_(scientist)' page we find link for "wiki/Augusta_Ada_Lovelace_Award", but not for "wiki/Ada_Lovelace", the one we have to look for.

Hope this clarifies.

**Comment by sdimitro** [comment]
but I do look only for /wiki/ ....
Look into Hamilton's html page and you will see:
<a href="/wiki/Ada_Lovelace" title="Ada Lovelace">Ada Lovelace</a> Ada_Lovelace

**Comment by aronwc** [comment]
The file Margaret_Hamilton_(scientist) does not have a link to Ada Lovelace. It's possible that the live version of the page on Wikipedia does, but it may have changed since these data were collected.

More generally, be sure that when you're matching the url to the list of names, you're comparing the entire string after the final / in the url.
E.g., wiki/Augusta_Ada_Lovelace_Award should look for Augusta_Ada_Lovelace_Award in the names set.

**Comment by sdimitro** [comment]
Oh I see. It is my fault because I used your fetch pages script before running pagerank.py.
I thought that since it is in our repo we had to run it first to fetch the data.
